[pytest]

#path and files
python_files = test_*.py *_test.
testpaths = ./project/

#classes and func
python_classes = Test* *_Test Test_* 
python_functions = test_* *_test

#extra options
addopts = --json-report --json-report-file=report.json

#marks
markers = 
    database_manager : Marca os testes que envolvem o DatabaseManager
    models : Marca os testes que envolvem os Models